encoding: utf-8

# SEO相关信息
title: LIA.IM
description: The stars, my destination.
keywords: LIA.IM,Blog,Html,JavaScript,PHP
author: Cyril Wong
footerText: 'LIA.IM.'

# 文章链接格式
permalink: /:title.html
kramdown:
  auto_ids: true
  input: GFM
  
# 忽略文件
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'cli.bat', 'dist.tar.gz']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: 'https://cyrilsoy.github.io'
baseurl: '/hello-jekyll'

# 菜单
menu:
  - title: 首页
    url: /
  - title: 归类
    url: /pages/categories.html
  - title: 搜索
    url: /pages/search.html
  - title: 友链
    url: /pages/links.html
  - title: RSS
    url: /static/xml/rss.xml
  - title: 关于
    url: /pages/about.html

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: false

# Google Adsense,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# 腾讯MTA移动分析,不需要请设置为false
# _includes/ext-mta.html 里面修改为自己的配置
extMTA: false

# 百度收录自动推送,不需要请设置为false
extBaidu: false

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: false

# 友情链接
links:
 - title: 拾柒
   url: https://iheo.net
 - title: 盒子萌
   url: https://www.boxmoe.com
 - title: 挖站否
   url: https://wzfou.com
